---
- name: loop test
  hosts: 112.172.54.131
  gather_facts: False
  tasks:
  - name: shell command - /usr/bin/foo
    shell: python3 --version
    register: result
    ignore_errors: True

  - debug:
      var=result

  - debug:
      msg: "{{ result.stderr }}"
      when: result.failed is failed

  - debug:
      msg: "{{ result.stdout }}"
      when: result.changed is changed
