---
- name: loop test
  hosts: 121.189.77.180
  gather_facts: False
  tasks:
  - name: shell command - /usr/bin/foo
    shell: /usr/bin/foo
    register: result
    ignore_errors: True

  - debug:
      msg: "failed"
      when: result is failed

  - debug:
      msg: "changed"
      when: result is changed
