---
- name: loop test
  hosts: 121.189.77.180
  remote_user: root
  gather_facts: False
  vars:
    file_path: /home/work/touch_file
  tasks:
  - name: create directory
    file:
      path: "{{ file_path }}"
      state: directory

  - name: create file
    file:
      path: "{{ file_path}}/{{ item }}.txt"
      state: touch
    loop:
    - first
    - second
    - third
    - test1
    - test2