---
# 사전 목록 loop 이용
- name: loop test
  hosts: 121.189.77.180
  gather_facts: False
  tasks:
  - debug:
      msg: "{{ item.user }} - {{ item.group }}"
    loop:
    - user: user1
      group: group1
    - user: user2
      group: group2
    