---
- name: loop test
  hosts: 121.189.77.180
  gather_facts: False
  vars:
    users:
    - user1
    - user2
    - user3
    dbs:
    - db1
    - db2
    - db3
  tasks:
  - debug:
      msg: "{{ item[0] }} - {{ item[1] }}"
    loop:
    - "{{ user | product( dbs ) | list }}"
     