---
- name: stat command test
  hosts: 172.30.1.24
  tasks:
  - name: Get stats of a file
    ansible.builtin.stat:
      path: /etc/foo.conf
      register: st

  - debug:
      var: st

  - name: Fail if the file does not belong to 'root'
    ansible.builtin.fail:
      msg: "Whoops! file ownership has changed"
    when: st.stat.pw_name != 'root'
